"""Generate a Linux GPU wheel lock from actual installation reports, without re-resolving."""

import importlib.metadata
import json
import re
from pathlib import Path


def normalize(name):
    return re.sub(r"[-_.]+", "-", name).lower()


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    active = {normalize(d.metadata["Name"]): d.version for d in importlib.metadata.distributions()}
    core = {}
    for line in (root / "requirements-dev.lock").read_text().splitlines():
        match = re.match(r"^([A-Za-z0-9_.-]+)==([^ ;\\]+)", line)
        if match:
            core[normalize(match[1])] = match[2]
    artifacts = {}
    for filename in ["gpu-install.json", "qiskit-compat-install.json"]:
        source = root / "reports/environment" / filename
        for item in json.loads(source.read_text())["install"]:
            name = normalize(item["metadata"]["name"])
            version = item["metadata"]["version"]
            if active.get(name) == version and name not in core:
                sha = item["download_info"]["archive_info"]["hashes"]["sha256"]
                assert re.fullmatch("[0-9a-f]{64}", sha)
                artifacts[name] = (version, sha, filename)
    missing = set(active) - set(core) - set(artifacts) - {"proofgate-pq"}
    assert not missing, f"Distributions without recorded wheel hashes: {sorted(missing)}"
    assert all(active.get(name) == version for name, version in core.items()), "Core lock drift"
    lines = [
        "# Linux x86_64 / Python 3.12; hashes of the wheels actually installed.",
        "# Generated by scripts/lock_installed_gpu.py from preserved pip --report records.",
        "# No driver or system CUDA package is installed by this lock.",
        "-r ../requirements-dev.lock",
        "",
    ]
    for name, (version, sha, source) in sorted(artifacts.items()):
        lines += [f"{name}=={version} --hash=sha256:{sha}", f"    # source: {source}"]
    (root / "environment/requirements-gpu.lock").write_text("\n".join(lines) + "\n")
    print(f"Locked {len(artifacts)} additional GPU/scientific distributions; core unchanged.")
